Added more questions on strings
TheSYNcoder/InterviewPrep pull request #16
Opened 2020-10-01 10:51 UTC by hanzala-sohrab

Added some more interview questions based on strings. Some questions were taken from the list which can be found [here](https://docs.google.com/document/d/1SM92efk8oDl8nyVw8NHPnbGexTS9W-1gmTEYfEurLWQ/edit).

2020-10-01 11:39 UTC, CubixPro commented
Hi thank you for your interest! Can you add the solutions to some of the links that you posted. Also it would be great if instead of creating a seperate credits heading you would add the link under the links/articles tab.

2020-10-01 11:53 UTC, TheSYNcoder requested changes
Please don't try to add new sections in the main README.md, you can add them continuing in a list 
no need of mentioning credits, please keep each point concise.

2020-10-01 13:48 UTC, hanzala-sohrab commented
Sure.
I will make the necessary changes.

2020-10-01 14:29 UTC, hanzala-sohrab commented
Okay, sure

2020-10-01 15:20 UTC, CubixPro commented
This looks great! @TheSYNcoder can you take a look and then we can merge.

2020-10-02 03:58 UTC, CubixPro commented on Topic/BST.md
> +* [K’th Largest element in BST using constant extra space](https://www.geeksforgeeks.org/kth-largest-element-bst-using-constant-extra-space/)
Solution?

2020-10-02 06:17 UTC, hanzala-sohrab commented on Topic/BST.md
> +* [K’th Largest element in BST using constant extra space](https://www.geeksforgeeks.org/kth-largest-element-bst-using-constant-extra-space/)
Added solution

2020-10-02 06:29 UTC, CubixPro commented
Thank you for your contribution!

2020-10-02 06:29 UTC, merged